swagger: '2.0'
info:
  title: Customer Info API Specification
  description: Swagger for Customer Info API Specification
  version: v1.0
basePath: /customer-info/v1.0
schemes:
  - https
consumes:
  - application/json; charset=utf-8
  - application/jose+jwe
produces:
  - application/json; charset=utf-8
  - application/jose+jwe
paths:
  /info:
    get:
      tags:
        - CustomerInfo
      summary: Get Customer info details
      operationId: GetCustomerInfo
      parameters:
        - $ref: '#/parameters/x-fapi-auth-date'
        - $ref: '#/parameters/x-fapi-customer-ip-address'
        - $ref: '#/parameters/x-fapi-interaction-id'
        - $ref: '#/parameters/Authorization'
        - $ref: '#/parameters/x-customer-user-agent'
      responses:
        '200':
          $ref: '#/responses/200CustomerInfoRead'
        '400':
          $ref: '#/responses/400Error'
        '401':
          $ref: '#/responses/401Error'
        '403':
          $ref: '#/responses/403Error'
        '404':
          $ref: '#/responses/404Error'
        '405':
          $ref: '#/responses/405Error'
        '406':
          $ref: '#/responses/406Error'
        '429':
          $ref: '#/responses/429Error'
        '500':
          $ref: '#/responses/500Error'
      security:
        - PSUOAuth2Security:
            - accounts
parameters:
  ConsentId:
    name: ConsentId
    in: path
    description: ConsentId
    required: true
    type: string
  AccountId:
    name: AccountId
    in: path
    description: AccountId
    required: true
    type: string
  Authorization:
    in: header
    name: Authorization
    type: string
    required: true
    description: 'An Authorisation Token as per https://tools.ietf.org/html/rfc6750'
  x-customer-user-agent:
    in: header
    name: x-customer-user-agent
    type: string
    description: Indicates the user-agent that the PSU is using.
    required: false
  x-fapi-customer-ip-address:
    in: header
    name: x-fapi-customer-ip-address
    type: string
    required: false
    description: "The PSU's IP address if the PSU is currently logged in with the TPP."
  x-fapi-auth-date:
    in: header
    name: x-fapi-auth-date
    type: string
    required: false
    description: "The time when the PSU last logged in with the TPP. \nAll dates in the HTTP headers are represented as RFC 7231 Full Dates. An example is below: \nSun, 10 Sep 2017 19:43:31 UTC"
    pattern: "^(Mon|Tue|Wed|Thu|Fri|Sat|Sun), \\d{2} (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \\d{4} \\d{2}:\\d{2}:\\d{2} (GMT|UTC)$"
  x-fapi-interaction-id:
    in: header
    name: x-fapi-interaction-id
    type: string
    required: false
    description: An RFC4122 UID used as a correlation id.
  x-idempotency-key:
    name: x-idempotency-key
    in: header
    description: |
      Every request will be processed only once per x-idempotency-key.  The
      Idempotency Key will be valid for 24 hours.
    required: true
    type: string
    pattern: "^(?!\\s)(.*)(\\S)$"
    maxLength: 40
  x-jws-signature:
    in: header
    name: x-jws-signature
    type: string
    required: true
    description: A detached JWS signature of the body of the payload.
responses:
  200CustomerInfoRead:
    description: Parties Read
    headers:
      x-fapi-interaction-id:
        type: string
        description: An RFC4122 UID used as a correlation id.
    schema:
      $ref: '#/definitions/ReadCustomerInfo'
  400Error:
    description: Bad request
    headers:
      x-fapi-interaction-id:
        type: string
        description: An RFC4122 UID used as a correlation id.
    schema:
      $ref: '#/definitions/ErrorResponse1'
  401Error:
    description: Unauthorized
    headers:
      x-fapi-interaction-id:
        type: string
        description: An RFC4122 UID used as a correlation id.
  403Error:
    description: Forbidden
    headers:
      x-fapi-interaction-id:
        type: string
        description: An RFC4122 UID used as a correlation id.
    schema:
      $ref: '#/definitions/ErrorResponse1'
  404Error:
    description: Not found
    headers:
      x-fapi-interaction-id:
        type: string
        description: An RFC4122 UID used as a correlation id.
  405Error:
    description: Method Not Allowed
    headers:
      x-fapi-interaction-id:
        type: string
        description: An RFC4122 UID used as a correlation id.
  406Error:
    description: Not Acceptable
    headers:
      x-fapi-interaction-id:
        type: string
        description: An RFC4122 UID used as a correlation id.
  415Error:
    description: Unsupported Media Type
    headers:
      x-fapi-interaction-id:
        type: string
        description: An RFC4122 UID used as a correlation id.
  429Error:
    description: Too Many Requests
    headers:
      Retry-After:
        description: Number in seconds to wait
        type: integer
      x-fapi-interaction-id:
        type: string
        description: An RFC4122 UID used as a correlation id.
  500Error:
    description: Internal Server Error
    headers:
      x-fapi-interaction-id:
        type: string
        description: An RFC4122 UID used as a correlation id.
    schema:
      $ref: '#/definitions/ErrorResponse1'
securityDefinitions:
  TPPOAuth2Security:
    type: oauth2
    flow: application
    tokenUrl: 'https://authserver.example/token'
    scopes:
      accounts: Ability to read Accounts information
    description: TPP client credential authorisation flow with the ASPSP
  PSUOAuth2Security:
    type: oauth2
    flow: accessCode
    tokenUrl: 'https://authserver.example/token'
    authorizationUrl: 'https://authserver.example/authorization'
    scopes:
      accounts: Ability to read Accounts information
    description: 'OAuth flow, it is required when the PSU needs to perform SCA with the ASPSP when a TPP wants to access an ASPSP resource owned by the PSU'
definitions:
  BuildingNumber:
    description: Number that identifies the position of a building on a street.
    type: string
    minLength: 1
    maxLength: 16
  CountryCode:
    description: 'Nation with its own government, occupying a particular territory.'
    type: string
    pattern: '^[A-Z]{2,2}$'
  CountrySubDivision:
    description: 'Identifies a subdivision of a country eg, state, region, county.'
    type: string
    minLength: 1
    maxLength: 35
  EmailAddress:
    description: Address for electronic mail (e-mail).
    type: string
    minLength: 1
    maxLength: 256
  FullLegalName:
    description: Specifies a character string with a maximum length of 350 characters.
    type: string
    minLength: 1
    maxLength: 350
  Links:
    type: object
    description: Links relevant to the payload
    additionalProperties: false
    required:
      - Self
  Meta:
    title: MetaData
    type: object
    description: Meta Data relevant to the payload
    additionalProperties: false
  Name_3:
    description: Name by which a party is known and which is usually used to identify that party.
    type: string
    minLength: 1
    maxLength: 70
  Title:
    description: Title of the party. The title of a person. e.g. Mr, Mrs, Reverend, Lieutenant Colonel.
    type: string
    minLength: 1
    maxLength: 70
  Initials:
    description: The initials of an Individual. eg. M.K.
    type: string
    minLength: 1
    maxLength: 70
  AddressTypeCode:
    description: Identifies the nature of the postal address.
    type: string
    enum:
      - Business
      - Correspondence
      - DeliveryTo
      - MailTo
      - POBox
      - Postal
      - Residential
      - Statement
  Error1:
    type: object
    properties:
      ErrorCode:
        description: 'Low level textual error code, e.g., Field.Missing'
        type: string
        x-namespaced-enum:
          - Field.Expected
          - Field.Invalid
          - Field.InvalidDate
          - Field.Missing
          - Field.Unexpected
          - Header.Invalid
          - Header.Missing
          - Reauthenticate
          - Resource.ConsentMismatch
          - Resource.InvalidConsentStatus
          - Resource.InvalidFormat
          - Resource.NotFound
          - Rules.AfterCutOffDateTime
          - Rules.DuplicateReference
          - Signature.Invalid
          - Signature.InvalidClaim
          - Signature.Malformed
          - Signature.Missing
          - Signature.MissingClaim
          - Signature.Unexpected
          - UnexpectedError
          - Unsupported.AccountIdentifier
          - Unsupported.AccountSecondaryIdentifier
          - Unsupported.Currency
          - Unsupported.Frequency
          - Unsupported.LocalInstrument
          - Unsupported.Scheme
      Message:
        description: |-
          A description of the error that occurred. e.g., 'A mandatory field isn't supplied' or 'RequestedExecutionDateTime must be in future'
        type: string
        minLength: 1
        maxLength: 500
      Path:
        description: 'Recommended but optional reference to the JSON Path of the field with error, e.g., Data.Initiation.InstructedAmount.Currency'
        type: string
        minLength: 1
        maxLength: 500
      Url:
        description: 'URL to help remediate the problem, or provide more information, or to API Reference, or help etc'
        type: string
    required:
      - ErrorCode
      - Message
    additionalProperties: false
    minProperties: 1
  ErrorResponse1:
    description: 'An array of detail error codes, and messages, and URLs to documentation to help remediation.'
    type: object
    properties:
      Code:
        description: 'High level textual error code, to help categorize the errors.'
        type: string
        minLength: 1
        maxLength: 40
      Id:
        description: 'A unique reference for the error instance, for audit purposes, in case of unknown/unclassified errors.'
        type: string
        minLength: 1
        maxLength: 40
      Message:
        description: "Brief Error message, e.g., 'There is something wrong with the request parameters provided'"
        type: string
        minLength: 1
        maxLength: 500
      Errors:
        items:
          $ref: '#/definitions/Error1'
        type: array
        minItems: 1
    required:
      - Code
      - Message
      - Errors
    additionalProperties: false
  CustomerInfo:
    type: object
    required:
      - party_id
    properties:
      party_id:
        $ref: "#/definitions/PartyId"
      title: 
        $ref: "#/definitions/Title"
      initials:
        $ref: "#/definitions/Initials"
      family_name:
        $ref: '#/definitions/Name_3'
      given_name:
        $ref: '#/definitions/Name_3'
      email:
        $ref: '#/definitions/EmailAddress'
      phone_number:
        $ref: '#/definitions/PhoneNumber_0'
      birthdate:
        type: 'string'
        format: date
      address:
          type: object
          description: Postal address of a party.
          required:
            - Country
          properties:
            address_type:
              $ref: '#/definitions/AddressTypeCode'
            street_address:
              type: array
              items:
                description: 'Information that locates and identifies a specific address, as defined by postal services, that is presented in free format text.'
                type: string
                minLength: 1
                maxLength: 70
              minItems: 0
              maxItems: 5
            postal_code:
              $ref: '#/definitions/PostCode'
            country:
              $ref: '#/definitions/CountryCode'
  ReadCustomerInfo:
    type: object
    required:
      - Data
    properties:
      Data:
        $ref: '#/definitions/CustomerInfo'
  PartyId:
    description: A unique and immutable identifier used to identify the customer resource. This identifier has no meaning to the account owner.
    type: string
    minLength: 1
    maxLength: 40
  PartyNumber:
    description: Number assigned by an agent to identify its customer.
    type: string
    minLength: 1
    maxLength: 35
  PhoneNumber_0:
    description: 'Collection of information that identifies a phone number, as defined by telecom services.'
    type: string
    pattern: "\\+[0-9]{1,3}-[0-9()+\\-]{1,30}"
  PhoneNumber_1:
    description: 'Collection of information that identifies a mobile phone number, as defined by telecom services.'
    type: string
    pattern: "\\+[0-9]{1,3}-[0-9()+\\-]{1,30}"
  PostCode:
    description: Identifier consisting of a group of letters and/or numbers that is added to a postal address to assist the sorting of mail.
    type: string
    minLength: 1
    maxLength: 16
  StreetName:
    description: Name of a street or thoroughfare.
    type: string
    minLength: 1
    maxLength: 70
  TownName:
    description: 'Name of a built-up area, with defined boundaries, and a local government.'
    type: string
    minLength: 1
    maxLength: 35
  